// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use remote Supabase for development (local storage has issues)
const SUPABASE_URL = "https://wpqetuxkjsmzxzuvybes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwcWV0dXhranNtenh6dXZ5YmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNjkwMDUsImV4cCI6MjA3NTY0NTAwNX0.8gsWGcV1D38fPFmmJAIINGSbVuF_H0Ukl43TuOXAkIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});